### ISSUE TITLE
[Randimals] Add support for bunnies, owls, and bats?

### ISSUE THREAD

**Issue by CreatorKami** [tmercswims/tmerc-cogs#52]
### I am submitting a...
```
 [ ] Bug report
 [x] Feature request or improvement for an existing cog
```

### Name of the cog in question:
Randimals

### Description of my issue/request:
I would like an option for bunnies, owls, and bat random images, please? Bunnies always make everyone feel better<3

### If it's a bug, steps to reproduce:
 
 1.

### If it's a bug, a stack trace:
```
Paste it here.
```

**Comment by tmercswims** [comment]
While I certainly don't disagree, this cog in particular is difficult to add to, because it requires an external API for the images. I keep my eye out for APIs that give a random image of certain animals, and add them when I find them, but deliberately searching for an API for a specific animal is usually fruitless, sadly :(

**Comment by tmercswims** [comment]
I am going to close this issue, but just know that I am always on the lookout for more animal APIs to add.

**Comment by CreatorKami** [comment]
@tmercswims I found this? http://shibe.online/

**Comment by tmercswims** [comment]
I already have cat and dog, but I used the bird part of that API to add a `[p]bird` command.
