### ISSUE TITLE
Get quotes globally

### ISSUE THREAD

**Issue by curryandrice** [tmercswims/tmerc-cogs#66]
### I am submitting a...
```
 [ ] Bug report
 [x] Feature request or improvement for an existing cog
```

### Name of the cog in question:
Quotes

### Description of my issue/request:
A command to post a random quote using all of the servers indexes, like a global version of [p]quote

### If it's a bug, steps to reproduce:
 
 1.

### If it's a bug, a stack trace:
```
Paste it here.
```

**Comment by tmercswims** [comment]
I don't really see the use for this. Most bots (>95%, if I had to guess) fall into one of two categories. The first is "only a member of a single server, because it's run by one person in that server for them and their friends" and the other is "a member of dozens of servers, because it is hosted by one person and purposefully made publicly available for anyone else to simply invite."

The use case for something like this request is for the very small subset of bots that are members of two or three different servers, which all have the same set of people in them. Because otherwise, why would you care what another servers quotes are? They wouldn't make sense to you. Besides the fact that there is a potential for privacy concerns, depending on what people put as quotes. It can give away names, addresses, private links or videos, or anything else that is fine to have when it's limited to your server only, but as soon as anyone else using the same bot can see it, it may become a problem.

So I must say no.

**Comment by skeith** [comment]
I think he might want this feature for selfbot

**Comment by curryandrice** [comment]
He actually kinda got it right its for a bot used across a large number of affiliated servers. But now that i look at it, the request would not be useful for the cog to the general public. Its because i use quotes differently in my servers. rather than actual quotes its aliased and used as a sort of custom command roulette. Since i couldn't find a proper cog for that.

**Comment by skeith** [comment]
Well at least for me, I use my selfbot to collect quotes (you'll see me collect quotes from Red server) and since I colect quotes for my selfbot, it makes sense for me wanting a global toggle. Unfortunately, I am not using your cog, so .. can't push this issue
