### ISSUE TITLE
Retake channels cog doesn't work. (Missing sourcemod command).

### ISSUE THREAD

**Issue by BiZR-TV** [tmercswims/tmerc-cogs#82]
### I am submitting a...
```
 [ X ] Bug report
 [ ] Feature request or improvement for an existing cog
```

### Name of the cog in question:
retakechannels

### Description of my issue/request:
Everything from the cog seems to work fine but will fail at the RCON part due to "sm_player_teams" not being a recognised command. Is that something private you have or is it part of a public addon? Couldn't find anything by googling the command

### If it's a bug, steps to reproduce:
 
 1.

### If it's a bug, a stack trace:
```
Unknown command "sm_player_teams"

**Comment by tmercswims** [comment]
Hey! Sorry about that. To be honest, I hadn't meant to release the retakechannels cog because I didn't think it would be super useful to anyone else. But since it's out there, I'm not going to take it away, haha. I published the SourceMod plugin that I wrote which is required for the cog to work, and you can grab it here: https://github.com/tmercswims/sm-player-teams
