### ISSUE TITLE
Customjoinleave does not load on bot start

### ISSUE THREAD

**Issue by pabloleban** [tmercswims/tmerc-cogs#84]
### I am submitting a...

- [x] Bug report
- [ ] Feature request or improvement for an existing cog

### Name of the cog in question: customjoinleave
customjoinleave starts unloaded and never loads unless it's loaded by an admin.

Is this a bug only affecting me?

**Comment by tmercswims** [comment]
It's not just you. This actually happens to me as well, and I haven't been able to track down exactly why. I _think_ (but I'm not sure) that it's actually a Red bug, because I've seen reports of the same thing happening to other people for random other cogs as well. (Random in the sense that they don't have anything in common - author, functionality, complexity, etc.) But since I haven't been able to pin it down, and since Red v3 will hopefully not have the same issue, I sort of just deal with it.

Sorry, I wish I could offer something more :(

**Comment by jack1142** [comment]
@tmercswims in my case, it's because there's no Audio cog on the time, when customjoinleave loads and it can't load its settings, because of it. Maybe you'll just check settings from Audio cog data file?

**Comment by tmercswims** [comment]
Good catch! Attempting to get the Audio cog before it is loaded is indeed what was causing this issue.
