### ISSUE TITLE
[V3] Randimals bird & cat (shibe.online) https problem

### ISSUE THREAD

**Issue by Mystard** [tmercswims/tmerc-cogs#88]
### I am submitting a...
```
 [✔] Bug report
 [ ] Feature request or improvement for an existing cog
```

### Name of the cog in question:
randimals

### Description of my issue/request:
shibe.online seems to be having problems with HTTPS, and while the code uses https the cog isn't able to retrieve a random bird or cat from shibe.online. `I was unable to get a bird picture.`
I believe this is a problem in shibe.online's end because browser yells about the unsafe cert too.
Using http instead of https fixes this and the images can be retrieved again: `url = 'http://shibe.online/api/birds?count=1'`

### If it's a bug, steps to reproduce:
 
 1. Try to retrieve a bird or cat image with `[p]cat`or `[p]bird`

(Additional info: Debian 8 Jessie, Red - Version 3.0.0b14, Python 3.5.3+)

**Comment by skeith** [comment]
~~I can't reproduce this. Cog works fine on my bot~~

~~Problem might lies on your bot host~~

~~Clarification, the method is the same with v2, since v2 works and the url is the same, should be fine on v3
I am trying on v3 later tomorrow morning~~

Tested, borked on v3
Preparing a fix

Now time for me to sleep
